### ISSUE TITLE
`parseDateTime` fails

### ISSUE THREAD

**Issue by akuckartz** [emir-munoz/tarql#4]
I executed

```
mvn install
```

but the result was:

```
Failed tests:   parseDateTime(org.deri.tarql.functions.ParseDateTest): expected:<Sun May 11 11:11:51 [I]ST 2014> but was:<Sun May 11 11:11:51 [CE]ST 2014>

Tests in error: 
  parseDate(org.deri.tarql.functions.ParseDateTest): Unparseable date: "1-May-07"
```

**Comment by emir-munoz** [comment]
Hi, thanks for reporting this. I will update the test later. For now you can skip the test executing

```
mvn install -DskipTests
```

NOTE: if you take a close look, the problem is the Time Zone "[I]ST" and "[CE]ST". That is because there is no Time Zone indicated in the string literal.
